#include <iostream>
#include <jni.h>
#include "HelloJNI.h"   // auto-generated by `javah HelloJNI`

using namespace std;

JNIEXPORT void JNICALL Java_HelloJNI_sayHello (JNIEnv *, jobject) {
    cout << "Hello world. from a Cpp program" << endl;
    return;
}